In [1]:
import numpy as np

nn=6; mm=6;

maxVal=20;

rowLines=[x for x in range(nn)]
colLines=[y for y in range(mm)]
assignments=[]
removedRows=[]
removedCols=[]

np.random.seed(500)
costMatrix=np.random.randint(maxVal,size=(nn,mm))

#ensure costMatrix is square
if nn<mm:
    #add rows of +M when nn<mm
    costMatrix=np.append(costMatrix,5*maxVal*np.ones((mm-nn,mm)),axis=0)
elif nn>mm:
    #add columns of zeros when mm<nn
    costMatrix=np.append(costMatrix,np.zeros((nn,nn-mm)),axis=1)

print(costMatrix)
OG_costMatrix=costMatrix.copy();

[[ 1 17 14  8  7 13]
 [13 17 17  9  2 10]
 [18 19 13  6  8 15]
 [10 14 13 13  2 13]
 [10 14 11  9  2 18]
 [15 15 19  5  5 16]]


In [2]:
for ind in range(max(nn,mm)):
    if ind <nn:
        #step 1: subtract min number in row from that row
        costMatrix[ind,:]=np.subtract(costMatrix[ind,:],costMatrix[ind,:].min())
    if ind <mm:
        #step 2: subtract min number in col from that col
        costMatrix[:,ind]=np.subtract(costMatrix[:,ind],costMatrix[:,ind].min())

print(costMatrix)

[[ 0  2  5  6  6  4]
 [11  1  7  6  0  0]
 [13  0  0  0  3  2]
 [10  0  5 12  2  5]
 [10  0  3  8  2 10]
 [14  0 10  3  4  7]]


In [3]:
while len(assignments)<max(nn,mm):
    #Step 4 (min is zero after step 2)
    ixgrid=np.ix_(rowLines,colLines)
    d=costMatrix[ixgrid].min()
    costMatrix[ixgrid]=np.subtract(costMatrix[ixgrid],d)
    for rowInd in removedRows:
        for colInd in removedCols:
            costMatrix[rowInd,colInd]+=d

    rowLines=[x for x in range(nn)]
    colLines=[y for y in range(mm)]
    removedRows=[]
    removedCols=[]
    assignments=[]

    #step 3: draw min number of lines to cover all zeros
    crossOutZeros=True
    while crossOutZeros:
        crossOutZeros=False

        ixgrid=np.ix_(rowLines,colLines)
        ##Used to "cross out" zeros
        subMatrix=5*maxVal*np.ones((nn,mm))
        subMatrix[ixgrid]=costMatrix[ixgrid]
        numRowZeros=np.count_nonzero(subMatrix==0,axis=1)
        numColZeros=np.count_nonzero(subMatrix==0,axis=0)

        maxNumRowZeros=np.amax(numRowZeros)
        maxNumColZeros=np.amax(numColZeros)
        if np.count_nonzero(numColZeros==1) < np.count_nonzero(numRowZeros==1):
            if maxNumRowZeros>0:
                rowToZero=np.where(numRowZeros==1)[0]
                crossOutZeros=True
                if len(rowToZero)>0:
                    colIndex=np.where(subMatrix[int(rowToZero[0]),:]==0)[0]
                    if len(colIndex)>0:
                        colLines.remove(int(colIndex[0]))
                        removedCols.append(int(colIndex[0]))
                        assignments.append((int(rowToZero[0]),int(colIndex[0])))
                else:
                    if maxNumRowZeros > maxNumColZeros:
                        rowToZero=np.where(numRowZeros==maxNumRowZeros)[0]
                        colIndex=np.where(subMatrix[int(rowToZero[0]),:]==0)[0]
                        if len(colIndex)>0:
                            colLines.remove(int(colIndex[0]))
                            removedCols.append(int(colIndex[0]))
                            assignments.append((int(rowToZero[0]),int(colIndex[0])))
                    else:
                        colToZero=np.where(numColZeros==maxNumColZeros)[0]
                        rowIndex=np.where(subMatrix[:,int(colToZero[0])]==0)[0]
                        if len(rowIndex)>0:
                            rowLines.remove(int(rowIndex[0]))
                            removedRows.append(int(rowIndex[0]))
                            assignments.append((int(rowIndex[0]),int(colToZero[0])))
        else:
            if maxNumColZeros>0:
                colToZero=np.where(numColZeros==1)[0]
                crossOutZeros=True
                if len(colToZero)>0:
                    rowIndex=np.where(subMatrix[:,int(colToZero[0])]==0)[0]
                    if len(rowIndex)>0:
                        rowLines.remove(int(rowIndex[0]))
                        removedRows.append(int(rowIndex[0]))
                        assignments.append((int(rowIndex[0]),int(colToZero[0])))
                else:
                    if maxNumColZeros > maxNumRowZeros:
                        colToZero=np.where(numColZeros==maxNumColZeros)[0]
                        rowIndex=np.where(subMatrix[int(colToZero[0]),:]==0)[0]
                        if len(rowIndex)>0:
                            colLines.remove(int(rowIndex[0]))
                            removedCols.append(int(rowIndex[0]))
                            assignments.append((int(rowIndex[0]),int(colToZero[0])))
                    else:
                        rowToZero=np.where(numRowZeros==maxNumRowZeros)[0]
                        colIndex=np.where(subMatrix[:,int(rowToZero[0])]==0)[0]
                        if len(colIndex)>0:
                            colLines.remove(int(colIndex[0]))
                            removedCols.append(int(colIndex[0]))
                            assignments.append((int(rowToZero[0]),int(colIndex[0])))

# ixgrid=np.ix_(rowLines,colLines)
# print(f"\nrowLines: {rowLines}")
# print(f"colLines: {colLines}")
# ##Used to "cross out" zeros
# subMatrix=5*maxVal*np.ones((nn,mm))
# subMatrix[ixgrid]=costMatrix[ixgrid]
# numRowZeros=np.count_nonzero(subMatrix==0,axis=1)
# numColZeros=np.count_nonzero(subMatrix==0,axis=0)
# print(f"submatrix: \n{subMatrix}")
# print(f"numRowZeros: {numRowZeros}")
# print(f"numColZeros: {numColZeros}")
print(f"cost matrix: \n{OG_costMatrix}\n")
print(f"assignments: {assignments}")
totalCost=0;
for assignment in assignments:
    totalCost+=OG_costMatrix[assignment]
print(f"""Total assignment cost: {totalCost}""")

cost matrix: 
[[ 1 17 14  8  7 13]
 [13 17 17  9  2 10]
 [18 19 13  6  8 15]
 [10 14 13 13  2 13]
 [10 14 11  9  2 18]
 [15 15 19  5  5 16]]

assignments: [(0, 0), (1, 5), (4, 3), (2, 2), (5, 1), (3, 4)]
Total assignment cost: 50
